export const NEW_CONTACT = 'NEW_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const DELETE_CONTACTS = 'DELETE_CONTACTS';
export const EDIT_CONTACT = 'EDIT_CONTACT';
